/*
* The GPLv3 licence :
* -----------------
* Copyright (c) 2009 Ricardo Dias
*
* This file is part of MuVis.
*
* MuVis is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* MuVis is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with MuVis.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * DirectoryListViewTreeUI.java
 *
 * Created on 11/Mai/2009, 12:42:08
 */

package muvis.view;

import muvis.view.directories.FileSystemTreeModel;
import muvis.view.directories.FileSystemTreeRender;

/**
 *
 * @author Ricardo
 */
public class DirectoryListViewTreeUI extends javax.swing.JPanel {

    /** Creates new form DirectoryListViewTreeUI */
    public DirectoryListViewTreeUI() {
        initComponents();

        FileSystemTreeModel model = new FileSystemTreeModel();
        FileSystemTreeRender renderer = new FileSystemTreeRender();

        treeDirectoryList.setModel(model);
        treeDirectoryList.setCellRenderer(renderer);
        treeDirectoryList.setRootVisible(false);
        treeDirectoryList.setShowsRootHandles(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listTreePanel = new javax.swing.JScrollPane();
        treeDirectoryList = new javax.swing.JTree();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(150, 300));

        treeDirectoryList.setModel(treeDirectoryList.getModel());
        treeDirectoryList.setMaximumSize(new java.awt.Dimension(1000, 64));
        listTreePanel.setViewportView(treeDirectoryList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listTreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listTreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane listTreePanel;
    protected javax.swing.JTree treeDirectoryList;
    // End of variables declaration//GEN-END:variables

}
