/*
* The GPLv3 licence :
* -----------------
* Copyright (c) 2009 Ricardo Dias
*
* This file is part of MuVis.
*
* MuVis is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* MuVis is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with MuVis.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * TreemapArtistInspectorViewUI.java
 *
 * Created on 14/Ago/2009, 15:19:44
 */

package muvis.view;

import java.util.ArrayList;

/**
 *
 * @author Ricardo
 */
public class TreemapArtistInspectorViewUI extends javax.swing.JPanel {

    /** Creates new form TreemapArtistInspectorViewUI */
    public TreemapArtistInspectorViewUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        artistNameLabel = new javax.swing.JLabel();
        seeAllArtistsButton = new javax.swing.JButton();
        albumsHolderPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        albumsInfoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        prevAlbumsButton = new javax.swing.JButton();
        albumPanel1 = new javax.swing.JPanel();
        albumButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        albumLabel1 = new javax.swing.JTextArea();
        albumPanel2 = new javax.swing.JPanel();
        albumButton2 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        albumLabel2 = new javax.swing.JTextArea();
        albumPanel3 = new javax.swing.JPanel();
        albumButton3 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        albumLabel3 = new javax.swing.JTextArea();
        albumPanel4 = new javax.swing.JPanel();
        albumButton4 = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        albumLabel4 = new javax.swing.JTextArea();
        nextAlbumsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tracksTableArtistInspector = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));

        artistNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        artistNameLabel.setText("Artist name");

        seeAllArtistsButton.setText("All artists");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artistNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(seeAllArtistsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seeAllArtistsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap())
        );

        albumsHolderPanel.setMaximumSize(new java.awt.Dimension(800, 305));

        albumsInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        albumsInfoLabel.setText("x - y / z Albuns , with q tracks.");
        albumsInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(albumsInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(albumsInfoLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        prevAlbumsButton.setText("<");
        prevAlbumsButton.setEnabled(false);
        prevAlbumsButton.setMaximumSize(new java.awt.Dimension(41, 265));
        prevAlbumsButton.setMinimumSize(new java.awt.Dimension(41, 265));
        prevAlbumsButton.setPreferredSize(new java.awt.Dimension(41, 265));
        jPanel1.add(prevAlbumsButton);

        albumButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Red-X.png"))); // NOI18N
        albumButton1.setEnabled(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(226, 76));

        albumLabel1.setBackground(new java.awt.Color(240, 240, 240));
        albumLabel1.setColumns(10);
        albumLabel1.setEditable(false);
        albumLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        albumLabel1.setLineWrap(true);
        albumLabel1.setRows(3);
        albumLabel1.setText("Album name");
        albumLabel1.setWrapStyleWord(true);
        albumLabel1.setBorder(null);
        albumLabel1.setEnabled(false);
        albumLabel1.setFocusable(false);
        albumLabel1.setOpaque(false);
        albumLabel1.setRequestFocusEnabled(false);
        albumLabel1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(albumLabel1);

        javax.swing.GroupLayout albumPanel1Layout = new javax.swing.GroupLayout(albumPanel1);
        albumPanel1.setLayout(albumPanel1Layout);
        albumPanel1Layout.setHorizontalGroup(
            albumPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(albumButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addGroup(albumPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        albumPanel1Layout.setVerticalGroup(
            albumPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumPanel1Layout.createSequentialGroup()
                .addComponent(albumButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(albumPanel1);

        albumButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Red-X.png"))); // NOI18N
        albumButton2.setEnabled(false);

        jScrollPane3.setBorder(null);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(226, 76));

        albumLabel2.setBackground(new java.awt.Color(240, 240, 240));
        albumLabel2.setColumns(10);
        albumLabel2.setEditable(false);
        albumLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        albumLabel2.setLineWrap(true);
        albumLabel2.setRows(3);
        albumLabel2.setText("Album name");
        albumLabel2.setWrapStyleWord(true);
        albumLabel2.setBorder(null);
        albumLabel2.setEnabled(false);
        albumLabel2.setFocusable(false);
        albumLabel2.setOpaque(false);
        albumLabel2.setRequestFocusEnabled(false);
        albumLabel2.setVerifyInputWhenFocusTarget(false);
        jScrollPane3.setViewportView(albumLabel2);

        javax.swing.GroupLayout albumPanel2Layout = new javax.swing.GroupLayout(albumPanel2);
        albumPanel2.setLayout(albumPanel2Layout);
        albumPanel2Layout.setHorizontalGroup(
            albumPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(albumButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, albumPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        albumPanel2Layout.setVerticalGroup(
            albumPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumPanel2Layout.createSequentialGroup()
                .addComponent(albumButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(albumPanel2);

        albumButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Red-X.png"))); // NOI18N
        albumButton3.setEnabled(false);

        jScrollPane4.setBorder(null);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(226, 76));

        albumLabel3.setBackground(new java.awt.Color(240, 240, 240));
        albumLabel3.setColumns(10);
        albumLabel3.setEditable(false);
        albumLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        albumLabel3.setLineWrap(true);
        albumLabel3.setRows(3);
        albumLabel3.setText("Album name");
        albumLabel3.setWrapStyleWord(true);
        albumLabel3.setBorder(null);
        albumLabel3.setEnabled(false);
        albumLabel3.setFocusable(false);
        albumLabel3.setOpaque(false);
        albumLabel3.setRequestFocusEnabled(false);
        albumLabel3.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setViewportView(albumLabel3);

        javax.swing.GroupLayout albumPanel3Layout = new javax.swing.GroupLayout(albumPanel3);
        albumPanel3.setLayout(albumPanel3Layout);
        albumPanel3Layout.setHorizontalGroup(
            albumPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(albumButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, albumPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        albumPanel3Layout.setVerticalGroup(
            albumPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumPanel3Layout.createSequentialGroup()
                .addComponent(albumButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(albumPanel3);

        albumPanel4.setPreferredSize(new java.awt.Dimension(150, 264));

        albumButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Red-X.png"))); // NOI18N
        albumButton4.setToolTipText("");
        albumButton4.setEnabled(false);
        albumButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane5.setBorder(null);
        jScrollPane5.setEnabled(false);
        jScrollPane5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(226, 76));

        albumLabel4.setBackground(new java.awt.Color(240, 240, 240));
        albumLabel4.setColumns(10);
        albumLabel4.setEditable(false);
        albumLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        albumLabel4.setLineWrap(true);
        albumLabel4.setRows(3);
        albumLabel4.setText("Album name");
        albumLabel4.setWrapStyleWord(true);
        albumLabel4.setBorder(null);
        albumLabel4.setEnabled(false);
        albumLabel4.setFocusable(false);
        albumLabel4.setOpaque(false);
        albumLabel4.setRequestFocusEnabled(false);
        albumLabel4.setVerifyInputWhenFocusTarget(false);
        jScrollPane5.setViewportView(albumLabel4);

        javax.swing.GroupLayout albumPanel4Layout = new javax.swing.GroupLayout(albumPanel4);
        albumPanel4.setLayout(albumPanel4Layout);
        albumPanel4Layout.setHorizontalGroup(
            albumPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumPanel4Layout.createSequentialGroup()
                .addGroup(albumPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(albumButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(albumPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        albumPanel4Layout.setVerticalGroup(
            albumPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(albumPanel4Layout.createSequentialGroup()
                .addComponent(albumButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(albumPanel4);

        nextAlbumsButton.setText(">");
        nextAlbumsButton.setEnabled(false);
        nextAlbumsButton.setMaximumSize(new java.awt.Dimension(41, 265));
        nextAlbumsButton.setMinimumSize(new java.awt.Dimension(41, 265));
        nextAlbumsButton.setPreferredSize(new java.awt.Dimension(41, 265));
        jPanel1.add(nextAlbumsButton);

        javax.swing.GroupLayout albumsHolderPanelLayout = new javax.swing.GroupLayout(albumsHolderPanel);
        albumsHolderPanel.setLayout(albumsHolderPanelLayout);
        albumsHolderPanelLayout.setHorizontalGroup(
            albumsHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(albumsHolderPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        albumsHolderPanelLayout.setVerticalGroup(
            albumsHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, albumsHolderPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tracksTableArtistInspector.setAutoCreateRowSorter(true);
        tracksTableArtistInspector.setModel(new ArtistInspectorTracksTableModel( new ArrayList<Integer>()));
        jScrollPane1.setViewportView(tracksTableArtistInspector);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(albumsHolderPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(albumsHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JToggleButton albumButton1;
    protected javax.swing.JToggleButton albumButton2;
    protected javax.swing.JToggleButton albumButton3;
    protected javax.swing.JToggleButton albumButton4;
    protected javax.swing.JTextArea albumLabel1;
    protected javax.swing.JTextArea albumLabel2;
    protected javax.swing.JTextArea albumLabel3;
    protected javax.swing.JTextArea albumLabel4;
    private javax.swing.JPanel albumPanel1;
    private javax.swing.JPanel albumPanel2;
    private javax.swing.JPanel albumPanel3;
    private javax.swing.JPanel albumPanel4;
    private javax.swing.JPanel albumsHolderPanel;
    protected javax.swing.JLabel albumsInfoLabel;
    protected javax.swing.JLabel artistNameLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    protected javax.swing.JButton nextAlbumsButton;
    protected javax.swing.JButton prevAlbumsButton;
    protected javax.swing.JButton seeAllArtistsButton;
    protected javax.swing.JTable tracksTableArtistInspector;
    // End of variables declaration//GEN-END:variables

}
